services:
  # DrupalConsoleCore Services
  console.translator_manager:
    class: Drupal\Console\Utils\TranslatorManager
  console.configuration_manager:
    class: Drupal\Console\Utils\ConfigurationManager
  console.drupal_checker:
      class: Drupal\Console\Utils\DrupalChecker
  console.requirement_checker:
    class: Drupal\Console\Utils\RequirementChecker
  console.chain_queue:
    class: Drupal\Console\Utils\ChainQueue
  console.nested_array:
    class: Drupal\Console\Utils\NestedArray
  # DrupalConsoleCore Commands
  console.about:
    class: Drupal\Console\Command\AboutCommand
    tags:
      - { name: console.command }
  console.list:
    class: Drupal\Console\Command\ListCommand
    tags:
      - { name: console.command }
  console.help:
    class: Drupal\Console\Command\HelpCommand
    tags:
      - { name: console.command }
  console.complete:
    class: Drupal\Console\Command\CompleteCommand
    tags:
      - { name: console.command }
  console.check:
    class: Drupal\Console\Command\CheckCommand
    arguments: ['@console.requirement_checker', '@console.chain_queue', '@console.configuration_manager']
    tags:
      - { name: console.command }
  console.init:
    class: Drupal\Console\Command\InitCommand
    arguments: ['@app.root']
    tags:
      - { name: console.command }
  console.settings_debug:
    class: Drupal\Console\Command\Settings\DebugCommand
    arguments: ['@console.configuration_manager', '@console.nested_array']
    tags:
      - { name: console.command }
  console.settings_set:
    class: Drupal\Console\Command\Settings\SetCommand
    arguments: ['@console.configuration_manager', '@console.nested_array']
    tags:
      - { name: console.command }
