---
commands:
  config:
    config-edit: ~
    config-export: 'config:export'
    config-get: 'config:debug CONFIG_NAME'
    config-import: 'config:import'
    config-list: 'config:debug'
    config-pull: ~
    config-set: 'config:override'
  core:
    archive-dump: ~
    archive-restore: ~
    browse: ~
    core-cli: ~
    core-config: ~
    core-cron: 'cron:execute'
    core-execute: 'exec'
    core-init: 'init'
    core-quick-drupal: 'chain --file=~/.console/chain/quick-start.yml'
    core-requirements: 'site:status'
    core-rsync: ~
    core-status: 'site:status'
    core-topic: ~
    drupal-directory: ~
    entity-updates: 'update:entities'
    help: help
    image-derive: ~
    image-flush: 'image:styles:flush'
    php-eval: ~
    php-script: ~
    queue-list: 'queue:debug'
    queue-run: 'queue:run'
    shell-alias: ~
    site-alias: ~
    site-install: 'site:install'
    site-set: ~
    site-ssh: ~
    twig-compile: ~
    updatedb: 'update:execute'
    updatedb-status: 'update:debug'
    variable-delete: ~
    variable-get: ~
    variable-set: 'config:override'
    version: '--version'
  drush_extras:
    block-configure: ~
    block-disable: ~
    block-show: ~
    copy-id: ~
    give-comment: ~
    give-node: ~
    grep: ~
    sql-compare: ~
    sql-hash: ~
  field:
    field-clone: ~
    field-create: ~
    field-delete: ~
    field-info: ~
    field-update: ~
  language:
    language-add: ~
    language-default: ~
    language-disable: ~
    language-enable: ~
    language-prefix: ~
  language_translations:
    language-export-translations: ~
    language-groups-info: ~
    language-import-translations: ~
    language-refresh-translations: ~
  make:
    make: ~
    make-convert: ~
    make-generate: ~
    make-lock: ~
    make-update: ~
  other:
    clean-modules: ~
    coder-format: ~
    coder-review: ~
    composer: ~
    registry-rebuild: ~
    vimrc-install: ~
    vimrc-tag-gen: ~
  pm:
    pm-disable: 'module:uninstall, theme:uninstall'
    pm-download: 'module:download, theme:download'
    pm-enable: 'module:install, theme:install'
    pm-info: ~
    pm-list: 'module:debug, theme:debug'
    pm-projectinfo: ~
    pm-refresh: ~
    pm-releasenotes: ~
    pm-releases: ~
    pm-uninstall: 'module:uninstall, theme:uninstall'
    pm-update: 'module:update, theme:update'
    pm-updatecode: ~
    pm-updatestatus: ~
  role:
    role-add-perm: ~
    role-create: ~
    role-delete: ~
    role-list: ~
    role-remove-perm: ~
  runserver:
    runserver: server
    sql-cli: 'database:client'
    sql-connect: 'database:connect'
    sql-create: ~
    sql-drop: 'database:drop'
    sql-dump: 'database:dump'
    sql-query: 'database:query'
    sql-sanitize: ~
    sql-sync: ~
  search:
    search-index: ~
    search-reindex: ~
    search-status: ~
  site_audit:
    audit_all: ~
    audit_best_practices: ~
    audit_block: ~
    audit_cache: ~
    audit_codebase: ~
    audit_content: ~
    audit_cron: ~
    audit_database: ~
    audit_extensions: ~
    audit_insights: ~
    audit_security: ~
    audit_status: ~
    audit_users: ~
    audit_views: ~
    audit_watchdog: ~
    cache-clear: 'cache:rebuild'
    cache-get: ~
    cache-rebuild: 'cache:rebuild'
    cache-set: ~
    site-audit-version: ~
  state:
    state-delete: 'state:delete'
    state-get: 'state:debug'
    state-set: 'state:override'
  user:
    user-add-role: ~
    user-block: ~
    user-cancel: ~
    user-create: ~
    user-information: ~
    user-login: 'user:login:url'
    user-password: ~
    user-remove-role: ~
    user-unblock: ~
  watchdog:
    watchdog-delete: 'database:log:clear'
    watchdog-list: ~
    watchdog-show: 'database:log:debug'
